<?php
/**
 * @file
 * Code for the Express Admin Notes Views feature.
 */

include_once 'express_editor_notes_views.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function express_editor_notes_views_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'express_editor_notes_views');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'admin_note', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('admin_note');
  foreach ($hooks as $h) {
    if (isset($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Change type filter from a text field to a select list.
 */
function express_editor_notes_views_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-express-editor-notes-page') {
    $form['type']['#type'] = 'select';
    $form['type']['#options'] = express_editor_note_types();
    unset($form['type']['#size']);
    $form['type']['#empty_option'] = 'All';
  }
}
