<?php
/**
 * @file
 * Code for the Express Admin Notes Views feature.
 */

include_once 'express_editor_notes_views.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function express_editor_notes_views_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'express_editor_notes_views');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'admin_note', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('admin_note');
  foreach ($hooks as $h) {
    if (isset($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
    }
  }
}
